### ISSUE TITLE
Sondage PO

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#102]
```[tasklist]
### Tasks
- [x] Créer un brouillon dans tally
- [x] Intégrer les retours de Juliette et Mélo
- [ ] Envoyer sondage sur Mattermost
```
