### ISSUE TITLE
Lancer l'appel à intra pour la certification de Mai

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#104]
```[tasklist]
### Tasks
- [x] Tester Tally pour reccueillir les candidatures @Amel
- [x] Tester DS @Amel
- [x] Communiquer sur les canaux mattermost @Fanny
```
