### ISSUE TITLE
Aide à l'orga du webinaire EIG

### ISSUE THREAD

**Issue by AmelAlili** [betagouv/animation-communaute#106]
Communiquer auprès de la communauté concernant le webinaire du 18/03
```[tasklist]
### Tasks
- [x] créer l'évènement sur l'agenda public
- [x] communiquer sur mattermost + Tchap
- [x] intègrer l'info dans la newsletter
```
