### ISSUE TITLE
Tchap <> Mattermost : Lister les fonctionnalités attendues

### ISSUE THREAD

**Issue by LucasCharrier** [betagouv/animation-communaute#108]
Ce qui est attendu:

- [x] Thread
- [ ] Webhook -> [exemple](https://github.com/numerique-gouv/tchap-bot-webhook/tree/main)
- [ ] Recherche
- [ ] automatisation (je ne sais pas si possible par Tchap en ce moment)

Ce qu'il faudra migrer : 
-  [ ] les bots/automatisations
-  [ ] comment conserve t on une possibilité d'avoir accès à l'historique des échanges ?

```[tasklist]
### Tasks
- [ ] Que faudrait-il migrer ?
- [ ] Quelles fonctionnalités sont attendues ?
```
