### ISSUE TITLE
Gestion de la Newsletter du 29/02

### ISSUE THREAD

**Issue by AmelAlili** [betagouv/animation-communaute#110]
```[tasklist]
### Tasks
- [x] mise en page sur brevo
- [x] envoi à la communauté
```

```[tasklist]
### Tasks
- [x] demande de relecture par l"équipe
```
