### ISSUE TITLE
Communiquer sur le guichet Accessibilité

### ISSUE THREAD

**Issue by astranchet** [betagouv/animation-communaute#124]
```[tasklist]
### Tasks
- [ ] Dans la newsletter
- [ ] Sur le canal accessibilité
- [ ] Dans la documentation (page financements)
- [ ] Dans nos supports de formations
```
