### ISSUE TITLE
Améliorer la page Formation de l'espace membre

### ISSUE THREAD

**Issue by astranchet** [betagouv/animation-communaute#125]
```[tasklist]
### Tasks
- [x] Mettre une jolie favicon
- [x] Permettre de lier vers une catégorie précise de formation (et aussi pouvoir revenir vers une catégorie quand on navigue entre une page formation et le listing)
- [x] Corriger le niveau de titre des cartes (devrait être de niveau h2 plutôt que h3 pour respecter la hiérarchie) dans le listing
- [x] Corriger le niveau de titre de la date (devrait être h2 plutôt que h3 pour respecter la hiérarchie) dans les pages Formations
- [x] Ajouter un pied de page à l'espace membre (pour respirer !)
- [x] Retirer le alt des images de formation (mettre un alt vide : elles sont plutôt décoratives, c'est redondant)
```
