### ISSUE TITLE
Organisation de la tournée beta à Lille

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#137]
Première semaine de Juillet

```[tasklist]
### Tasks
- [x] Message à la communauté lilloise pour voir si les personnes sont intéressées
- [x] Recensement des lieux possibles
- [ ] https://github.com/betagouv/animation-communaute/issues/211
- [ ] https://github.com/betagouv/animation-communaute/issues/263
- [x] Réserver un lieu
- [ ] https://github.com/betagouv/animation-communaute/issues/258
- [ ] https://github.com/betagouv/animation-communaute/issues/259
- [ ] https://github.com/betagouv/animation-communaute/issues/262
- [ ] https://github.com/betagouv/animation-communaute/issues/261
```
