### ISSUE TITLE
Organiser la journée des incubateurs S1 2024

### ISSUE THREAD

**Issue by marinepurson2** [betagouv/animation-communaute#143]
```[tasklist]
### Tasks
- [x] Envoyer un Save the date : lundi 10 juin
- [x] Réserver un lieu : Lieu de la transfo (coloc + petite salle)
- [ ] https://github.com/betagouv/animation-communaute/issues/142
- [ ] https://github.com/betagouv/animation-communaute/issues/192
- [ ] https://github.com/betagouv/animation-communaute/issues/238
- [ ] https://github.com/betagouv/animation-communaute/issues/271
- [ ] https://github.com/betagouv/animation-communaute/issues/278
- [x] 27/05 : commander un petit-déjeuner
- [x] 27/05 : commander un déjeuner
- [ ] https://github.com/betagouv/animation-communaute/issues/287
```
