### ISSUE TITLE
Déléguer le process welcome to the jungle

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/animation-communaute#145]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/185
- [ ] https://github.com/betagouv/animation-communaute/issues/197
- [ ] changement de la doc
- [x] Informer les responsables d'incubateurs
- [x] Contacter les reponsables d'incubateur individuellement @Fanny
- [ ] https://github.com/betagouv/animation-communaute/issues/257
- [ ] Envoyer le replay aux responsables
```
