### ISSUE TITLE
Baisser les demandes de suivi coté badge

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/animation-communaute#146]
```[tasklist]
### Tasks
- [x] Commander un ordinateur pour l'ISN avec accès à Origami
- [x] Checker l'ordinateur de Marielle (ou le nôtre si on l'obtient) de façon hebdomadaire pour voir les réponses
- [x] Mieux comprendre le process de badge
- [x] Badge temporaire : process via airtable
```
