### ISSUE TITLE
Un process structuré pour le support

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/animation-communaute#147]
```[tasklist]
### Tasks
- [x] Qu'est ce qui se passe sur la page d'accueil de l'espac emembre
- [x] formulaire tally pour préqualifier la demande (en commun avec le formulaire deamnde ops)
- [x] inspecter crisp pou chatwoot
- [x] Choisir entre crisp et chatwoot
- [x] Avoir un process clair et simplifié de demande d'aide (un canal et un chat, un mail et faire une automatisation dans mattermost pour indiquer les bons canaux)
- [ ] Avoir un formulaire de préqualification dans le chat ou indiquer bonne pratique dans le canal
- [ ] Faire la campagne de com + fermer les canaux
```

**Comment by Benjamin-Doberset** [comment]
Utilisation de l'IA pour pouvoir améliorer les responsables
Travail sur les stats
Pas mal de demande pour utiliser des services 
Des demandes pour entrer dans le programme beta
Des demandes pour le mail
Pas encore utilisation de la faq
