### ISSUE TITLE
Organiser le forum en ligne

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#161]
```[tasklist]
### Tasks
- [x] Construire espace sur workadventure
- [x] Demander un devis pour workadventure
- [ ] https://github.com/betagouv/animation-communaute/issues/354
- [ ] https://github.com/betagouv/animation-communaute/issues/355
```
