### ISSUE TITLE
Organisation de la soirée communauté du 6 juin

### ISSUE THREAD

**Issue by marinepurson2** [betagouv/animation-communaute#166]
```[tasklist]
### Tasks
- [x] Réserver un lieu
- [x] Passer la commande
- [x] Créer un event pour que les gens puissent s'inscrire
- [x] Communiquer sur l'event
- [ ] https://github.com/betagouv/animation-communaute/issues/200
- [ ] https://github.com/betagouv/animation-communaute/issues/201
- [ ] https://github.com/betagouv/animation-communaute/issues/276
- [ ] https://github.com/betagouv/animation-communaute/issues/275
```
