### ISSUE TITLE
Cadrer le besoin des opérateurs pour organiser un event

### ISSUE THREAD

**Issue by marinepurson2** [betagouv/animation-communaute#167]
```[tasklist]
### Tasks
- [x] Réunion du 05/
- [x] Envoyer un CR
- [ ] https://github.com/betagouv/animation-communaute/issues/274
- [ ] https://github.com/betagouv/animation-communaute/issues/203
```
