### ISSUE TITLE
30% des membres de la communauté se sont inscrits à des événements beta (inclut formations, tournées…)

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#170]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/242
- [ ] https://github.com/betagouv/animation-communaute/issues/243
- [ ] Cibler 3 populations qui viennent moins
```
