### ISSUE TITLE
50% des coachs sont formés aux standards de qualité

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#174]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/249
- [ ] https://github.com/betagouv/animation-communaute/issues/250
- [ ] https://github.com/betagouv/animation-communaute/issues/251
```
