### ISSUE TITLE
100% des nouveaux membres ont participé à un embarquement beta.gouv.fr

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#176]
```[tasklist]
### Tasks
- [ ] Pouvoir lister les nouveaux membres
- [ ] Identifier ceux qui n'ont jamais participé à l'embarquement
- [ ] Créer suffisamment de sessions // nombre de nouveaux
- [ ] Structurer un embarquement plus important
```
