### ISSUE TITLE
50% des nouveaux membres ont été en contact avec une personne ressource lors du recrutement.

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#177]
```[tasklist]
### Comment on mesure ?
- [ ] Faire de la doc recrutement : comment établir une offre, comment sélectionner un profil, comment mener un entretien
- [ ] Ecrire un process de recrutement
- [ ] S'appuuyer sur les respo et les attributaires pour le suivi de ce process
- [ ] Mesure : taux d'offres pas top sur WTTJ, > 50% des recrutement sans entretien tech.
```

```[tasklist]
### Comment on fait ?
```

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/214
```
