### ISSUE TITLE
Constituer des jurys pour la certification de Mai

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#189]
```[tasklist]
### Tasks
- [x] Alexandra Oujebbour
- [x] Elodie Briche
- [x] Antoine de Zélicourt
- [x] Frédérique Williams
- [x] Gael de Vos
- [x] Manon Galle
- [x] Marine Jouan
- [x] Mathieu Fernandez
- [x] Patricia Bona
- [x] Sandrine David
- [x] Sophie Havreng
- [x] Thibaud Chambert-Loir
```
