### ISSUE TITLE
Revoir le forum ouvert / préparer le forum du 6 juin

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#193]
```[tasklist]
### Tasks
- [ ] Communiquer sur un programme clair
- [ ] Penser l'atelier "écrire la charte engagement écologique beta.gouv.fr" @Benjamin
- [x] Demander à Anne So si elle veut faire la formation figma
- [ ] Confirmer la présence de météo France @Fanny
- [x] voir si on peut commander le ptit dej ailleurs qu'au Paradis du Gourmand
- [x] voir avec les partenaires ce qu'ils veulent faire du standup
- [ ] penser le nouveau format de prise de notes @marine
```
