### ISSUE TITLE
Organiser l'événement du 26 Février

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#20]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/52
- [ ] https://github.com/betagouv/animation-communaute/issues/55
- [x] RDV avec la DSAF 5 Février
- [x] Préparer budget consolidé pour l'événement
- [x] Ecrire le déroulé technique : à envoyer à la DSAF le lundi 19/02 (@Marine)
- [x] Session de coordination avec l'équipe FAST : ordre du jour, invités, catering
- [x] Posters pour les incubateurs @Amel
- [x] Etiquettes pour chacun des participants @Amel
- [x] Finaliser la répartition du matériel @fanny et @marine
- [x] Imprimer certificats intras @fanny
- [x] Clôturer les inscriptions
- [x] Envoyer la liste des participants à la DSAF
- [x] Envoyer une confirmation d'inscription aux inscrits @marine
- [x] Fanny : Préparer texte à dire sur scène avec Paul
- [x] Imprimer les listes d'inscrits pour les hôtesses @fanny et @amel
- [x] Faire des photos le jour de l'événement -> mission communication @lucas
- [x] apporter tout ce qui est dans le casier animation a l'amphithéâtre à partir de 14h @amel @fanny
```
