### ISSUE TITLE
Récupérer de l'information des attributaires

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/animation-communaute#205]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/208
- [ ] https://github.com/betagouv/animation-communaute/issues/209
- [ ] Commencer le plan pour récupérer de l'info qualitative des livrables
```
