### ISSUE TITLE
Parcours intra

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#215]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/245
- [ ] https://github.com/betagouv/animation-communaute/issues/246
- [ ] https://github.com/betagouv/animation-communaute/issues/247
```
