### ISSUE TITLE
Renforcer l'inclusion/diversité dans la communauté

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/animation-communaute#216]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/217
- [ ] https://github.com/betagouv/animation-communaute/issues/218
- [ ] Donner les éléments auxquels penser lors d'une recherche de profil
```
