### ISSUE TITLE
Préparer Numérique en commun (NEC)

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/animation-communaute#231]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/291
- [ ] https://github.com/betagouv/animation-communaute/issues/289
- [ ] https://github.com/betagouv/animation-communaute/issues/290
- [x] Pour le NEC off : finaliser les contenus des ateliers
- [x] Pour les pitchs NEC : valider le format
- [ ] https://github.com/betagouv/animation-communaute/issues/379
- [ ] https://github.com/betagouv/animation-communaute/issues/390
- [ ] https://github.com/betagouv/animation-communaute/issues/391
- [ ] https://github.com/betagouv/animation-communaute/issues/397
- [ ] https://github.com/betagouv/animation-communaute/issues/396
```
