### ISSUE TITLE
Faire un plan de com pour beta.gouv.fr

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/animation-communaute#233]
```[tasklist]
### Tasks
- [x] Ecrire la strat de com 2025
- [ ] https://github.com/betagouv/animation-communaute/issues/554
- [x] Relecture Ben
- [x] Présentation équipe
- [ ] Répartition des points avec Divine
```
