### ISSUE TITLE
Repositionner et refonder l'espace membre

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/animation-communaute#236]
```[tasklist]
### Tasks
- [ ] Valider la / les propositions de valeur de l'espace membre
- [ ] Voir le sintégrations avec les outils développer par l'opérateur
- [ ] Quel différence avec un crm / etn  ?
```
