### ISSUE TITLE
Produire des contenus sur les standards

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#249]
```[tasklist]
### Tasks
- [x] MAJ la doc sur les standards de qualité (rationnaliser)
- [ ] Produire une vidéo de présentation et d'explication des standards
- [ ] Concevoir une présentation des standards pour animer des webinaires
- [ ] Concevoir une présentation des standards pour animer des webinaires
```
