### ISSUE TITLE
Communiquer sur les standards

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#250]
```[tasklist]
### Tasks
- [ ] Envoyer la liste détaillée des standards aux coachs (via une newsletter dédiée)
- [ ] Demander à Mael et Adrien s'ils peuvent nous envoyer la liste des coachs
- [ ] Organiser 3 webinaires pour former les coachs sur les standards
- [ ] Faire présenter les standards à 3 clubs coachs
```
