### ISSUE TITLE
Améliorer l'onboarding

### ISSUE THREAD

**Issue by astranchet** [betagouv/animation-communaute#252]
```[tasklist]
### Tasks
- [x] Screenshoter le parcours actuel
- [x] Identifier les axes d'amélioration
- [ ] https://github.com/betagouv/espace-membre-next/issues/174
- [x] Ne plus avoir de Github PR : WIP https://github.com/betagouv/espace-membre-next/pull/197
- [ ] https://github.com/betagouv/espace-membre-next/issues/216
- [ ] https://github.com/betagouv/espace-membre-next/issues/217
- [ ] https://github.com/betagouv/espace-membre-next/issues/218
```
