### ISSUE TITLE
(Re)lancer le programme Tandem Designer

### ISSUE THREAD

**Issue by astranchet** [betagouv/animation-communaute#256]
```[tasklist]
### Tasks
- [x] Préparer le questionnaire
- [x] Communiquer sur Mattermost
- [x] Communiquer sur la newsletter
- [ ] Faire les premiers matchs
```
