### ISSUE TITLE
Contacter les institutions et activités à Lille

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#263]
```[tasklist]
### Tasks
- [ ] Demander à la Halle de l'emploi quels interlocuteurs ils ont au niveau de Lille Métropole @Amel
- [ ] Visite de quartier
- [ ] Jeux du Nord
- [ ] Visite brasserie
- [x] Sciences Po Lille
- [x] Euratechnologies
```
