### ISSUE TITLE
Analyse primaire du sondage de la communauté

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#272]
```[tasklist]
### Tasks
- [x] Ta place chez beta.gouv @fanny
- [x] Les outils de la communauté @Amel
- [x] Les événements et formations @Amel
- [x] Les activités transverses de la communauté @Marine
- [x] Ton avis compte @Fanny
```
