### ISSUE TITLE
Sondage bien être communauté Octobre 2024

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#282]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/450
- [x] Retours équipe
- [ ] https://github.com/betagouv/animation-communaute/issues/458
- [ ] https://github.com/betagouv/animation-communaute/issues/467
- [ ] https://github.com/betagouv/animation-communaute/issues/468
- [ ] https://github.com/betagouv/animation-communaute/issues/473
- [x] Rappel sondage dans la NL du 28/10
- [ ] https://github.com/betagouv/animation-communaute/issues/488
- [x] Fermer le sondage
- [ ] https://github.com/betagouv/animation-communaute/issues/519
```
