### ISSUE TITLE
Préparer notre présence sur le stand DINUM au NEC

### ISSUE THREAD

**Issue by marinepurson2** [betagouv/animation-communaute#290]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/303
- [ ] https://github.com/betagouv/animation-communaute/issues/309
- [ ] https://github.com/betagouv/animation-communaute/issues/392
```
