### ISSUE TITLE
Restructurer la doc.incubateur.net

### ISSUE THREAD

**Issue by marinepurson2** [betagouv/animation-communaute#297]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/298
- [ ] https://github.com/betagouv/animation-communaute/issues/353
- [ ] https://github.com/betagouv/animation-communaute/issues/374
- [ ] https://github.com/betagouv/animation-communaute/issues/380
- [ ] Mettre en prod la nouvelle arborescence
```
