### ISSUE TITLE
KR 1 : 100% du MVP Espace membre terminé

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#310]
```[tasklist]
### Tasks
- [x] 100 % des fonctionnalités du mvp sont disponibles : créer, modifier les trois types de fiches avec migration de la BDD
- [ ] 100 % des cas d’usages mvp documenté
- [ ] Embarquement plus fluide  Onboarding: c’est fluide, plus de soucis d’email en liste noire, de compte mattermost inaccessible. On commence à voir pour avoir le suivi des accès matomo/sentry
```
