### ISSUE TITLE
Comment virer quelqu’un : définir un cadre juridique et de bonnes pratiques (@Fanny Blanc)

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#317]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/195
- [ ] https://github.com/betagouv/animation-communaute/issues/196
- [ ] https://github.com/betagouv/animation-communaute/issues/184
- [ ] https://github.com/betagouv/animation-communaute/issues/307
- [ ] https://github.com/betagouv/animation-communaute/issues/306
- [ ] https://github.com/betagouv/animation-communaute/issues/269
```
