### ISSUE TITLE
Certifier nos standards: Réformer la certification (@Fanny Blanc)

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#318]
```[tasklist]
### Tasks
- [x] Valider profil de Fanny et retrouver les accès à la France Compétences
- [x] Proposer changement : "agent" au lieu de "agent public"
- [x] Proposer changement : ajouter une ligne - validation par les pairs
```
