### ISSUE TITLE
KR 8 : 2 process d’embarquement finalisés

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#320]
```[tasklist]
### Tasks
- [ ] Formation approche beta @Fanny Blanc @Amel ALILI
- [ ] Valider les référents recrutement : 10 / compétence
- [ ] 1 process de recrutement @Benjamin Doberset
- [ ] https://github.com/betagouv/animation-communaute/issues/296
```
