### ISSUE TITLE
KR 11 : 1 feuille de route support et 1 automatisation

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#321]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/322
- [ ] Automatisation avec crisp
- [ ] Automatiser le support
- [ ] https://github.com/betagouv/animation-communaute/issues/147
```
