### ISSUE TITLE
KR 15 : Organiser 6 événements de la rentrée

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#324]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/161
- [ ] https://github.com/betagouv/animation-communaute/issues/348
- [ ] https://github.com/betagouv/animation-communaute/issues/350
- [ ] https://github.com/betagouv/animation-communaute/issues/231
- [ ] https://github.com/betagouv/animation-communaute/issues/401
- [ ] https://github.com/betagouv/animation-communaute/issues/351
- [ ] https://github.com/betagouv/animation-communaute/issues/361
```
