### ISSUE TITLE
KR 2 : 3 évolutions du mvp

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/animation-communaute#327]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/326
- [ ] https://github.com/betagouv/animation-communaute/issues/328
- [ ] Embarquement plus fluide Onboarding: c’est fluide, plus de soucis d’email en liste noire, de compte mattermost inaccessible.
- [ ] Automatiser sentry / matomo
- [ ] https://github.com/betagouv/animation-communaute/issues/386
```
