### ISSUE TITLE
KR 4 : Avoir 4 doc en plus sur les standards

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/animation-communaute#329]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/315
- [ ] https://github.com/betagouv/animation-communaute/issues/312
- [ ] https://github.com/betagouv/animation-communaute/issues/314
- [ ] https://github.com/betagouv/animation-communaute/issues/317
- [ ] https://github.com/betagouv/animation-communaute/issues/66
- [ ] à faire si temps en plus : https://github.com/orgs/betagouv/projects/82/views/14?filterQuery=Julien&layout=board&pane=issue&itemId=70170440
- [ ] https://github.com/betagouv/animation-communaute/issues/371
```
