### ISSUE TITLE
KR 5 : 100 % du site accessible

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/animation-communaute#330]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/313
- [ ] https://github.com/betagouv/animation-communaute/issues/93
- [x] Mettre à jour les pages incubateurs du site #240
- [ ] https://github.com/betagouv/animation-communaute/issues/239
- [ ] https://github.com/betagouv/animation-communaute/issues/240
```
