### ISSUE TITLE
KR9 : 10 référents recrutements validés par compétence.

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/animation-communaute#333]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/334
- [ ] Demande aux incubateurs
- [ ] Validation par les personnes compétentes
```
