### ISSUE TITLE
KR 10 : 1 process de recrutement

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/animation-communaute#335]
```[tasklist]
### Tasks
- [ ] voir avec chaib et gauthier pour bizdev
- [ ] https://github.com/betagouv/animation-communaute/issues/336
- [ ] https://github.com/betagouv/animation-communaute/issues/337
- [ ] une grille d'entretien culture coach
- [ ] une grille d'entretien tech coach
```
