### ISSUE TITLE
100% de la feuille route mail : Espace-membre : travaux desk/régie/OPI

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/animation-communaute#339]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/342
- [ ] https://github.com/betagouv/animation-communaute/issues/237
- [x] Test migration pour julien
- [ ] https://github.com/betagouv/animation-communaute/issues/381
- [ ] Test pour toute la ocmmunauté
```
