### ISSUE TITLE
dashlane

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/animation-communaute#340]
```[tasklist]
### Tasks
- [x] Ecrire la doc
- [x] Envoyer un message à tous les utilisateurs de dashlane
- [x] voir avec julien D si on peut permettre le transfert des mdp pro ou si trop dangereux
- [x] Demander devis à ED
- [ ] https://github.com/betagouv/animation-communaute/issues/389
- [ ] https://github.com/betagouv/animation-communaute/issues/399
- [ ] https://github.com/betagouv/animation-communaute/issues/398
```

```[tasklist]
### Tasks
```
