### ISSUE TITLE
matomo

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/animation-communaute#341]
```[tasklist]
### Tasks
- [ ] Avoir une doc du process
- [ ] Avoir finaliser la premiere migration avec ED
- [ ] Avoir fait migrer le 15 plus gros consommateurs
- [ ] https://github.com/betagouv/animation-communaute/issues/347
```

**Comment by revolunet** [comment]
je pense qu'on peut close ce sujet
