### ISSUE TITLE
Journée des incubateurs 20/11

### ISSUE THREAD

**Issue by marinepurson2** [betagouv/animation-communaute#361]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/362
- [ ] https://github.com/betagouv/animation-communaute/issues/363
- [ ] https://github.com/betagouv/animation-communaute/issues/400
- [ ] https://github.com/betagouv/animation-communaute/issues/404
- [ ] https://github.com/betagouv/animation-communaute/issues/405
- [ ] https://github.com/betagouv/animation-communaute/issues/406
- [ ] https://github.com/betagouv/animation-communaute/issues/499
- [x] Faire la présentation journée incubateurs
- [x] Lister les choses à apporter
- [ ] https://github.com/betagouv/animation-communaute/issues/524
```
