### ISSUE TITLE
BEN Liste à faire

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/animation-communaute#376]
```[tasklist]
### A faire
- [x] Transformer en bdd la liste des lieux 17 octobre
- [ ] https://github.com/betagouv/animation-communaute/issues/377
- [x] Ecrire un mini lius puis réunion pour savoir pourquoi on fait un meetup
- [x] envoyer mail isabelle 	 2:37 PM     KAMIL Isabelle (Sous-directrice) - DGALN/DEB/EARM isabelle.kamil@developpement-durable.gouv.fr
- [x] attente retour outils julien et lucas
- [x] attente rteour subvention findpe
- [x] publication message sur regles sur signature + intra (atention à ne pas confondre les genres)
- [x] publication message sur regles sur signature + intra (atention à ne pas confondre les genres)
- [x] pres anne so et amel sur referent
- [x] vérif julien à envoyer mail dashlane
- [x] message à alice sur le classement de grist (statut / projet
- [x] message à fanny pour valider les denrieres missions
- [x] email : st-ce que la commande est bien passée ?
- [x] to do : mettre à jour la note appel à intra sur docs
- [x] faire un point d"étape dans le cnala tchap lundi pour appel intra avec amélie
- [x] proces srecrutement pour remplacement fanny
- [x] faire les sf pour les mails et le cloud (bien accès) ovh
- [x] demander la regle sur les logements à boris
- [x] recevoir certification numa avant noel
- [x] FDM et Etat de frais
- [x] Budget !!
```

```[tasklist]
### En attente
- [x] Financement pour finacoop : quellle ligne (aic ou findpe) => aic
- [x] Devis OVH mail (14k) et cloud (27k HT qui deviendront via l'ugap 26 k TTC)
```

```[tasklist]
### Budget
- [x] Signer PV scopyleft juillet une fois qu'ona l'explicaiton du delta (PV plsu élévé que la conso)
- [x] Livrables pour signer pv final octo
- [x] PV partiel d'octo à déposer dans grist : en attente d'un action de leur part
- [x] attente de deux devis de la part de scopyleft (animaiton et sécurité)
- [x] avoir tableua octo suivi à jour et comprendre pourquoi markup change entre février et mars (mail envoyé 22/03
- [x] Attente devis bug biounty scopyleft
- [x] aexplication d'audrey car j'ai un pv de 136k pour mars mai, une facture de 129k et une conso de 129k mais différente de celle de la fatcure (la fcature est toujours non payée coté scopyleft mais le pv est validé coté nous)
```

```[tasklist]
### Tasks
- [ ] Envoye rmail insp pour proposer formation
- [x] Envoyer mail sylvie
- [x] Envoyer mail laure
```
```[tasklist]
### Tasks
- [ ] octo trend 2204
- [ ] accesibilité octo
```

```[tasklist]
### Appart location
- [x] Trouver clé
- [x] Reprendre etat des lieux d'entrée
```

```[tasklist]
### Tasks
- [x] Etat frais nec : recevoir facture ishan
- [x] Verif paiement Rennes / Nantes
- [x] Verif paiement ODM Lyon (envoyé en lai)
- [x] Verif paiement ODM bordeaux (envoyé en juin)
- [x] Verif paiement ODM séminaire
- [x] Paiement frais soirée 6 juin
- [ ] paiement séminaire équiê
```
