### ISSUE TITLE
Facuiliter l'accès à Google ads via dentsu

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/animation-communaute#388]
```[tasklist]
### Tasks
- [ ] Faire un bilan de ce qui ne fonctionne pas et de qui l'utilise
- [ ] Demander aux SIG le contact
- [ ] Voir avec gaspard si ok de le faire avec moi
```
