### ISSUE TITLE
Préparer l'arrivée de Divine

### ISSUE THREAD

**Issue by marinepurson2** [betagouv/animation-communaute#394]
```[tasklist]
### Tasks
- [x] Demander du matériel informatique
- [x] Préparer le planning S1
- [x] Créer son compte sur l'espace membre
- [x] Caler des temps de visio avec l'équipe (avec envoi invits)
```
