### ISSUE TITLE
Corriger l'accessibilité des sites beta.gouv.fr

### ISSUE THREAD

**Issue by astranchet** [betagouv/animation-communaute#41]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/43
- [x] Demander à Benoît si il peut nous faire un audit pour le site beta.gouv.fr
- [x] Lancer le devis de Idéance
- [x] Corriger un max de choses avant l'audit de la rentrée
- [ ] Mettre à jour la déclaration d'accessibilité
```
