### ISSUE TITLE
Faire vivre le guide de la communauté

### ISSUE THREAD

**Issue by marinepurson2** [betagouv/animation-communaute#410]
```[tasklist]
### Tasks
- [ ] Lancer un format de mise à jour de la doc sur Mattermost
- [ ] Intégrer une rubrique doc à la newsletter
- [ ] Mieux suivre les clics dans la doc (utile/pas utile, à jour ou pas...)
- [ ] Post Mattermost - process mise à jour doc
```
