### ISSUE TITLE
Créer une photothèque beta.gouv.fr

### ISSUE THREAD

**Issue by marinepurson2** [betagouv/animation-communaute#411]
```[tasklist]
### Tasks
- [x] Identifier un outil
- [ ] https://github.com/betagouv/animation-communaute/issues/447
- [ ] https://github.com/betagouv/animation-communaute/issues/480
- [x] Lister les dysfonctionnements
- [x] Partager la photothèque à l'ISN
- [ ] https://github.com/betagouv/animation-communaute/issues/513
- [ ] https://github.com/betagouv/animation-communaute/issues/551
- [ ] https://github.com/betagouv/animation-communaute/issues/558
- [ ] Communiquer sur la photothèque dans la newsletter
```

**Comment by dtende** [comment]
Voir avec @marinepurson2 et @LucasCharrier pourquoi certaines photos ne sont pas admises par la plateforme

**Comment by marinepurson2** [comment]
@revolunet on a un problème avec Immich : lorsqu'on crée un album, il faut le partager manuellement en ajoutant les adresses des personnes. On aimerait pouvoir rendre des albums ou photos "public" par défaut. Est-ce que c'est possible ?

**Comment by revolunet** [comment]
Tout est expliqué ici : https://immich.app/docs/features/shared-albums/

**Comment by marinepurson2** [comment]
Merci @revolunet ! Il y a souvent des erreurs 503 sur l'outil, je ne sais pas à quoi ça correspond. Sinon profite bien du Maroc !!

**Comment by marinepurson2** [comment]
![Image](https://github.com/user-attachments/assets/9172f6c1-270d-4dd8-8cff-f0ac08e2c247)
 Et il y a des fichiers qui ne chargent pas, sans explication

**Comment by revolunet** [comment]
@marinepurson2 tu peux stp m'envoyer un des fichiers qui ne passe pas ? j'imagine qu'il y a une limite de taille

**Comment by revolunet** [comment]
new url: https://images.incubateur.net
