### ISSUE TITLE
70 % de taux d’ouverture de la newsletter

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#417]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/434
- [x] Tester 3 nouveaux formats sur les 3 prochaines newsletters
- [x] Changer le jour d'envoi
- [x] Partager la newsletter aux respos d'incubateurs
```
