### ISSUE TITLE
Finaliser la préparation de la future migration mails pour la commu

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#419]
```[tasklist]
### Tasks
- [x] OPI: interface people pour ajouter/révoquer des membres de @beta.gouv.fr
- [x] setup domaine ext.beta.gouv.fr
- [ ] espace-membre: gérer le cas où un email est de type OPI cf https://github.com/betagouv/espace-membre-next/pull/707
- [ ] @ext.beta.gouv.fr sur la régie
- [ ] OPI: API people pour ajouter/révoquer des membres de @beta.gouv.fr
- [ ] OPI: integration people et ProConnect, pouvoir enroler des utilisateurs avec leur email secondaire
- [ ] espace-membre: utiliser l'auth ProConnect
- [ ] doc: adapter les [instructions de migration](https://pad.numerique.gouv.fr/gNoqGv9GTP22y5LLaajO-w#) pour la communauté
- [ ] définir la politique pour ext.beta.gouv.fr
```

**Comment by revolunet** [comment]
https://pad.numerique.gouv.fr/jZBIUYtRRXOLOlFn6NSxsA?both
