### ISSUE TITLE
Avoir testé une journée d’embarquement en présentiel

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#426]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/441
- [x] Faire le point sur tous les changements outils liés au nouvel embarquement
- [ ] https://github.com/betagouv/animation-communaute/issues/496
```
