### ISSUE TITLE
Un parcours de formation proposé à tous les nouveaux intras

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#429]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/433
- [x] Identifier les formations manquantes
- [ ] Développer les formations
```
