### ISSUE TITLE
Une investigation terminée sur “comment évaluer le coach” avec un respopo

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#430]
```[tasklist]
### Tasks
- [x] Retrouver le sondage déjà écrit
- [x] Demander à Margot de le tester en club respopo
- [ ] https://github.com/betagouv/animation-communaute/issues/491
- [ ] Collecter les retours
```

**Comment by fannyblanc** [comment]
Voici le sondage test 

https://tally.so/r/m6LXeP
