### ISSUE TITLE
Créer le nouveau template de la newsletter

### ISSUE THREAD

**Issue by marinepurson2** [betagouv/animation-communaute#434]
```[tasklist]
### Tasks
- [x] effectuer les modifications
- [x] Tester le nouveau template avec 3 personnes de l'équipe animation ou ISN
- [x] Ajuster le PAD collaboratif pour la prochaine newsletter
```

**Comment by dtende** [comment]
Il faudrait voir les modifications à effectuer @marinepurson2

**Comment by marinepurson2** [comment]
Les rubriques que tu proposes sont intéressantes.

Voici ce que j'ai commencé à lister à axes d'amélioration : 
- revoir l'ordre d'apparition des rubriques : 

1. Actus
2. Focus produit (ou Pause info, on peut alterner une sur deux ou selon l'actu)
3.  Evénements
4. Formation
5. Le problème du mois (un seul, sinon la newsletter va être trop longue)
6. Contacts utiles

- règle générale : ne pas écrire en rouge sang (c'est associé à la correction)
- concernant le design, il est préférable de reste dans les 3 couleurs majeures qui sont dans le template (bleu, bleu clair et rouge clair)

**Comment by dtende** [comment]
@marinepurson2 modifications effectuées.  Concernant la partie  info ou produit, je pense faire une mention spéciale dans le pad et garder le même format juste en adaptant le contenu dans la newsletter

**Comment by marinepurson2** [comment]
Bonne idée ! @lucascharrier-betagouv tu pourrais nous fournir le template du PAD qui est envoyé pour la newsletter à la commu ? On reste sur le format actuel pour la newsletter qui sera envoyée le mardi 29 mais on voudrait modifier des choses à partir de la newsletter du 12 novembre :)

**Comment by marinepurson2** [comment]
Sur le template, @dtende :
- Je préfèrerais qu'on garde les emojis dans les titres de rubrique pour alléger un peu visuellement.
- Dans les noms de rubrique, peux-tu ajouter les accents manquants et vérifier quand on met au pluriel ou au singulier (par ex. il faut passer événements au pluriel) ?
- Ce serait bien d'utiliser le bloc bleu que tu as utilisé pour Nos gestes climat pour mettre en avant soit "Minute info" soit "Focus produit" : il faut régler les espaces + y intégrer un titre de rubrique.
- Rubrique formation : ne pas centrer le texte (notamment parce que ce n'est pas accessible).

**Comment by dtende** [comment]
@marinepurson2 modifications effectuées
