### ISSUE TITLE
Organiser la certification de novembre

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#440]
```[tasklist]
### Tasks
- [x] Pre-entretien avec Camille
- [ ] https://github.com/betagouv/animation-communaute/issues/453
- [ ] https://github.com/betagouv/animation-communaute/issues/454
- [ ] https://github.com/betagouv/animation-communaute/issues/452
- [ ] https://github.com/betagouv/animation-communaute/issues/446
- [ ] https://github.com/betagouv/animation-communaute/issues/455
- [ ] https://github.com/betagouv/animation-communaute/issues/456
- [x] Répondre email pour candidat
- [ ] https://github.com/betagouv/animation-communaute/issues/457
- [ ] https://github.com/betagouv/animation-communaute/issues/494
- [x] Vérifier que tout le monde a bien reçu l'invitation google agenda
- [ ] Reboucler avec les jurés pour voir comment ça s'est passé
```
