### ISSUE TITLE
Recruter la/les remplaçant.e.s de Fanny

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#461]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/462
- [ ] https://github.com/betagouv/animation-communaute/issues/463
- [x] Consulter la team pour voir si aligné.e.s sur les fiches de poste
- [x] Publier sur WTTJ
- [x] Sélectionner les profils
- [x] Faire passer les entretiens
- [x] Sélectionner la / les personnes
- [ ] Passation
```
