### ISSUE TITLE
Bilan 2025

### ISSUE THREAD

**Issue by marinepurson2** [betagouv/animation-communaute#471]
```[tasklist]
### SNIN
- [ ] https://github.com/betagouv/animation-communaute/issues/536
- [x] Mettre en place un comité de sélection des SNIN
- [x] Identifier avec les équipes SNIN les bons indicateurs d'impact
- [x] Envoyer V1 bilan à Ishan
- [x] Plan de diffusion du bilan
```

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by marinepurson2** [comment]
- Essayer d'objectiver le fait qu'on ne répond pas qu'à des commandes gouvernementales : montrer d'où viennent nos sujets, la place des intras.
