### ISSUE TITLE
Finir l'embarquement initial

### ISSUE THREAD

**Issue by marinepurson2** [betagouv/animation-communaute#475]
```[tasklist]
### Tasks
- [ ] Formations obligatoires DSAF
- [ ] Accès au compte congès RH : aller voir le service informatique
- [x] Installer un gestionnaire de mots de passe : https://doc.incubateur.net/communaute/les-outils-de-la-communaute/autres-services/vaultwarden
```
