### ISSUE TITLE
Forum en ligne

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#508]
```[tasklist]
### Tasks
- [x] Contacter WA pour avoir un devis
- [ ] documents pour paiement à envoyer à Ben
- [ ] Régler pb enregistrement
- [ ] Préparer Com
```
