### ISSUE TITLE
Test outil audit tech ANCT

### ISSUE THREAD

**Issue by revolunet** [betagouv/animation-communaute#510]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/animation-communaute/issues/509
- [x] déploiement sur https://audit-tech.incubateur.net
- [ ] evaluer l'outil avec une startup : CDTN
- [ ] précréer les audits pour toutes les SE DINUM et impact national
```

**Comment by revolunet** [comment]
Test d'une version minimale pour récolter les 8 standards par @freesteph

**Comment by Benjamin-Doberset** [comment]
version allégée par rapport à l'anct car trop lourd, ensuite remontée dans la fiche produit

**Comment by freesteph** [comment]
post-mortem : on a fait https://github.com/beta/standards & https://github.com/betagouv/auto-audit parce que : 

* le backend de Grist pour les questions n'est pas pratique : 
  * l'édition de plain text dans un tableur est pénible
  * pas de support markdown
  * pas d'historique, d'authoring, de versionnage sur nos standards qu'on devait retravailler de toute façon (d'où repo dédié)
  * chaque produit et son audit doivent être recréés afin de partager une URL accessible à tous.
* on a pro-connecté notre outil + la DB de l'EspaceMembre ce qui nous permet d'être à jour avec les membres, les équipes et leurs produits.
  
Leur frontend est assez dense parce que l'ANCT fournit un accompagnement beaucoup plus proche derrière (ce qui n'est pas notre but) :

![Image](https://github.com/user-attachments/assets/cf1f1e32-872a-4774-a8d8-6bf1f27d8140)

Le notre est volontairement simpliste pour nous permettre de récolter et traiter les résultats de toute la communauté :

![Image](https://github.com/user-attachments/assets/28c80e9e-aa2b-4023-afdf-778424c974ff)
