### ISSUE TITLE
Monter un calendrier éditorial LinkedIn pour fin 2024-S1 2025

### ISSUE THREAD

**Issue by marinepurson2** [betagouv/animation-communaute#515]
```[tasklist]
### Tasks
- [x] Répartir les formats dans le calendrier éditorial LinkedIn
- [x] Identifier des produits pour #lundiproduit
- [x] Rédiger le post intrapreneur
- [x] Faire un message pour le canal LinkedIn mattermost (#lundiproduit)
- [ ] https://github.com/betagouv/animation-communaute/issues/528
- [ ] https://github.com/betagouv/animation-communaute/issues/529
- [ ] https://github.com/betagouv/animation-communaute/issues/530
```

**Comment by marinepurson2** [comment]
@dtende J'ai mis des commentaires dans le benchmark : https://pad.numerique.gouv.fr/FMhHTiLlTtuG1VFxq5syjg?both 
Sur cette base, peux-tu proposer un planning éditorial dans notre outil Mattermost, sur une base de 3 posts maximum par semaine ?

**Comment by dtende** [comment]
en cours de construction : https://www.notion.so/betagouv-dinum/13859e111b8b80c790a6d8ebb7adac8a?v=13859e111b8b8094bba2000c983e1ba9

**Comment by dtende** [comment]
@marinepurson2 

Voici le post rédigé : 

**BONNE SEMAINE DE L'ENTREPRENEURIAT !**

Eh oui, il n’y a pas que les startups qui célèbrent cette semaine ! Chez Beta.gouv.fr, nous aussi on célébre la semaine de l'entrepreneuriat et nos **129** intrapreneurs, dont le nombre ne cesse de croître au sein de la communauté et qui s'engagent pour faciliter l’accès et l’usage des services publics pour tous.

Vous avez déjà sûrement utilisé Démarches-simplifiées, Pix, le Pass Culture... Eh bien, tous ces produits qui nous accompagnent au quotidien, c’est grâce à eux !

**Mais qu'est-ce qu'un intrapreneur ?**

Un intrapreneur est un agent public qui identifie une problématique au sein de son administration et qui, fort de son expertise, propose une solution numérique pour y répondre.

**Pourquoi son rôle est-il primordial ?**

1. Sans intrapreneurs, difficile de répondre aux besoins évolutifs des administrations.
2. Sans intrapreneurs, difficile de comprendre les usagers pour leur proposer des solutions adaptées qui facilitent leur quotidien.
3. Sans intrapreneurs, difficile pour le service public de relever les enjeux et défis auxquels notre société est confrontée aujourd'hui et se verra confrontée demain.

Si cette lecture vous a donné envie d’en savoir plus sur les initiatives menées par des intrapreneurs, nous vous invitons à découvrir **l’interview de 2022 d’Emmanuel Flahaut,** qui nous parle de la création de Trackdéchets qui  permet d’assurer la traçabilité des déchets entièrement en ligne : [Parole d’intrapreneurs #12 : Emmanuel Flahaut de Trackdéchets — beta.gouv.fr - l'actualité](https://blog.beta.gouv.fr/general/2022/01/14/parole-d-intrapreneurs-12-emmanuel-flahaut-de-trackdechets/)

À tous nos intrapreneurs, merci !

**Comment by marinepurson2** [comment]
**C'est la semaine de l'entrepreneuriat !** 💪

Et le saviez-vous ❓ Dans le réseau @beta.gouv.fr, plus de 120 intrapreneurs s'engagent au quotidien pour construire des services publics numériques utiles, simples, faciles à utiliser et qui répondent vraiment aux besoins des gens.

Démarches simplifiées, Pix, le @Pass Culture, @Dossier facile... et bien d'autres produits que vous connaissez ont été conçus grâce à eux !

**Mais qu'est-ce qu'un intrapreneur ❓**
Un intrapreneur est un agent public qui identifie une problématique au sein de son administration et qui, fort de son expertise, propose une solution numérique pour y répondre.

**Pourquoi leur rôle est-il primordial ❓**
Sans intrapreneurs, difficile de comprendre les usagers pour leur proposer des solutions adaptées qui facilitent leur quotidien.
Sans intrapreneurs, difficile de répondre aux besoins évolutifs des administrations.

🔎 Pour mieux comprendre ce qu'est l'intrapreneuriat et les défis que relèvent les intrapreneurs du réseau beta.gouv.fr, (re)découvrez l'interview d’Emmanuel Flahaut, qui nous parlait en 2022 de la création de Trackdéchets, un service qui permet d’assurer la traçabilité des déchets dangereux : [Parole d’intrapreneurs #12 : Emmanuel Flahaut de Trackdéchets — beta.gouv.fr - l'actualité](https://blog.beta.gouv.fr/general/2022/01/14/parole-d-intrapreneurs-12-emmanuel-flahaut-de-trackdechets/)

**Comment by marinepurson2** [comment]
@dtende voici le post avec mes ajustements ! Merci ! 

Tu peux le programmer pour lundi sur le compte LinkedIn ? Et l'ajouter dans le calendrier édito partagé sur Mattermost ?
