### ISSUE TITLE
Communication forum 12 décembre

### ISSUE THREAD

**Issue by marinepurson2** [betagouv/animation-communaute#518]
```[tasklist]
### Tasks
- [x] Créer un programme
- [x] 14/11 : 1e com Mattermost + Tchap
- [x] 21/11 : relance
- [x] 28/11 : relance
- [x] 10/12 : mail aux inscrits avec programme
- [x] Préparer pitch d'intro du forum du 12 décembre
```
