### ISSUE TITLE
Préfiguration 10 ans beta.gouv.fr

### ISSUE THREAD

**Issue by marinepurson2** [betagouv/animation-communaute#521]
```[tasklist]
### Tasks
- [x] Caler une date pour une réunion 10 ans ISN
- [x] Préparer un atelier avec benchmark des possibles
- [x] Ecrire une note pour présenter le projet 10 ans avec déroulé à la DINUM
- [x] Réservation Cité fertile
```
