### ISSUE TITLE
nettoyage brevo

### ISSUE THREAD

**Issue by revolunet** [betagouv/animation-communaute#555]
```[tasklist]
### Tasks
- [ ] supprimer les comptes partagés de Brevo
- [ ] créer des comptes séparés par application
- [ ] limiter les admins
- [ ] activer le 2FA
- [ ] utiliser des adresses dédiées pour chaque app
```

**Comment by Benjamin-Doberset** [comment]
divisée le gros sous compte communauté en plusieurs sous comptes (un pour vaultwarden, un pour espace mebre etc) : voir la pertinence de ce qui est demandé par Julien D, attention à ne pas consommer trop de sous comptes

**Comment by Benjamin-Doberset** [comment]
permettrait d'éviter les problemes de délivrabilité en ayant une adresse mail 
éviter d'avoir une adresse de connexion commune
