### ISSUE TITLE
Suivre l'accompagnement en accessibilité

### ISSUE THREAD

**Issue by astranchet** [betagouv/animation-communaute#90]
```[tasklist]
### Tasks
- [x] Mettre en place un CRM de suivi dans notion
- [ ] Échanger avec les respospos concernés
- [ ] Initier une prise de contact avec chacune des équipes concernées
```
