### ISSUE TITLE
Création d'un Pad pour les ressources utiles pour les Intras

### ISSUE THREAD

**Issue by AmelAlili** [betagouv/animation-communaute#94]
Centraliser les documentations utiles pour les intrapreneurs, accessibles via l'espace membre
```[tasklist]
### Tasks
- [x] https://pad.numerique.gouv.fr/s/jKamXivzf
- [x] Demander la contribution des Respospos
- [ ] Integrer le pad à l'espace membre
```
